### PR TITLE
Feature/add support for keep alive

### PR DESCRIPTION
**Pull request by sshivananda**
Adding clientSessionKeepAlive - See https://docs.snowflake.net/manuals/user-guide/nodejs-driver-use.html#required-connection-options

### CODE REVIEW

**Comment by sshivananda** [comment]
@natesilva Should I bump the snowflake-sdk as well ? Or should that be a separate PR?

**Comment by natesilva** [comment]
Should we also add `clientSessionKeepAliveHeartbeatFrequency`? I wish there was a TypeScript definition for `snowflake-sdk` so we don’t have to keep updating this.

**Comment by sshivananda** [comment]
Updated the PR to include clientSessionKeepAliveHeartbeatFrequency.

**Comment by sshivananda** [comment]
Agree on the bit about typescript definitions for the `snowflake-sdk` repo - a lot of the code in the repo is also dedicated to typechecking.

**Comment by sshivananda** [comment]
@natesilva Have you had a chance to take a look at this one?

**Comment by natesilva** [comment]
Thank you! This will be published on npm in a few minutes.

**Pull request merged**
