### PR TITLE
Add insecureConnect option

### PR DESCRIPTION
**Pull request by fredericbarthelet**
Updating configureOption typing to include `insecureConnect` option as per documentation : https://community.snowflake.com/s/article/How-to-turn-off-OCSP-checking-in-Snowflake-client-drivers

### CODE REVIEW

**Comment by natesilva** [comment]
Thank you! This will be released shortly. Out of curiosity, were you seeing OCSP errors on Snowflake connections recently?

**Comment by fredericbarthelet** [comment]
Thanks @natesilva.
I'm in fact currently (and since May approximately) experiencing difficulty with OCSP on Snowflake. No error in particular, but rather long OCSP validation time. Snowflake is in fact checking OCSP at connection, at each request, and at connection closing time. Each validation requires communication with a few CA servers, having response time larger than 1s each sometimes.

Are you experiencing similar problems ?

**Comment by sshivananda** [comment]
@fredericbarthelet  - I have been facing issues with connectivity.  I don't want to set this in my app - but I will try this out and reach out to snowflake - if this turns out to be the root cause behind the issues.

**Comment by natesilva** [comment]
We’ve seen a handful of OCSP errors but I haven’t been able to reliably duplicate them.

**Pull request merged**
